@startuml
left to right direction
skinparam packageStyle rectangle


actor cliente
actor agente

rectangle "Sistema aluguel de carros" {   
  usecase "UC01 - efetuar pedido" as UC01
  usecase "UC02 - modificar pedido" as UC02
  usecase "UC03 - cancelar pedido" as UC03
  usecase "UC04 - analisar pedido" as UC04
  usecase "UC05 - avaliar pedido" as UC05
  usecase "UC06 - registrar parecer" as UC06
  usecase "UC07 - aceitar contrato" as UC07
  usecase "UC08 - escolher modalidade de contrato" as UC08
}   

cliente --> (UC01)
cliente --> (UC02)
cliente --> (UC03)
cliente --> (UC07)
cliente --> (UC08)
agente --> (UC04)
agente --> (UC05)
agente --> (UC06)
(UC01) --> agente
@enduml