@startuml
left to right direction
skinparam packageStyle rectangle

actor Usuario
actor Cliente
actor Agente

Cliente --|> Usuario
Agente --|> Usuario

rectangle "Sistema de aluguel de carros" {
    usecase "UC01 - Efetuar pedido" as UC01
    usecase "UC02 - Modificar pedido" as UC02
    usecase "UC03 - Cancelar pedido" as UC03
    usecase "UC04 - Analisar pedido" as UC04
    usecase "UC05 - Avaliar pedido" as UC05
    usecase "UC06 - Registrar parecer" as UC06
    usecase "UC07 - Aceitar contrato" as UC07
    usecase "UC08 - Escolher modalidade de contrato" as UC08
    usecase "UC09 - Gerenciar conta" as UC09
    usecase "UC10 - Consultar pedidos" as UC10
}

Usuario --> UC09

Cliente --> UC01
Cliente --> UC02
Cliente --> UC03
Cliente --> UC07
Cliente --> UC08
Cliente --> UC10

Agente --> UC04
Agente --> UC05
Agente --> UC06

@enduml