@startuml
class Agente{
  -nome: String
  +aprovarPedido(pedido Pedido): boolean
}

class Cliente{
  -RG: String
  -CPF: String
  -nome: String
  -endereco: String
  -profissão: String
  -empregadores: List
  -pedidos: List
}

class Banco{
  -nome: String
  +aprovarContratoCredito(): boolean
}

class Automovel{
  -placa: String
  -ano: Int
  -marca: String
  -modelo: String
  -emUso: boolean
  +setEmUso(emUso boolean): boolean
}


class Contrato{
  -modalidade: ModalidadeContrato
  -contratante: Cliente
  -automovel: Automovel
  +reservaAutomovel(): void
}

enum ModalidadeContrato {
  LOCACAO
  ASSINATURA
  LEASING
}

class Locacao{
  -dataInicio: LocalDate 
  -dataFim: LocalDate 
  +devolucaoAutomovel(): void
}

class Assinatura{
  -valorMensalidade: Double 
  -dataFim: LocalDate 
  +devolucaoAutomovel(): void
}

class Empregador{
  -nome: String
  -rendimento: Double
}

class Pedido{
  -dataCriacao: LocalDate
  +estaAvaliado(): boolean
}

enum StatusPedido {
  CRIADO
  AVALIADO
  APROVADO
  RECUSADO
  CANCELADO
}

Pedido   "1"    -- "0..1" Contrato  
Cliente  "1"    -- "1..n" Empregador
Cliente  "1"    -- "0..*" Pedido
Cliente -- Locacao
Banco -- Locacao
Locacao -- Assinatura
Assinatura -- Automovel
Agente  -- Banco
Contrato "0..1" -- "1" Automovel

@enduml