@startuml
class Agente{
  -nome: String
  +aprovarPedido(pedido Pedido): boolean
}

class Banco{
  +aprovarContratoCredito(): boolean
}

class Automevel{
  -placa: String
  -ano: Int
  -marca: String
  -modelo: String
  -emUso: boolean
  +setEmUso(emUso boolean): boolean
}

class Contratante {
  -RG: String
  -CPF: String
  -nome: String
  -endereco: String
  -profissão: String
  -empregadores: List
  -pedidos: List
}

class Contrato{
  #contratante: Contratante
  #automocel: Automevel
  +reservaAutomovel(): void
}

class Locacao{
  -dataInicio: LocalDate 
  -dataFim: LocalDate 
  +devolucaoAutomovel(): void
}

class Assinatura{
  -valorMensalidade: Double 
  -dataFim: LocalDate 
  +devolucaoAutomovel(): void
}

class Empregador{
  -nome: String
  -rendimento: Double
}

class Pedido{

}
@enduml